//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electric_Scooter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
            this.Points = new HashSet<Points>();
        }
    
        public int o_Id { get; set; }
        public string o_No { get; set; }
        public Nullable<System.DateTime> o_Date { get; set; }
        public Nullable<int> o_c_Id { get; set; }
        public string o_State { get; set; }
        public Nullable<int> o_TotalPrice { get; set; }
        public Nullable<bool> o_IsSettled { get; set; }
        public Nullable<bool> o_IsCollectPayment { get; set; }
        public Nullable<bool> o_IsInstallment { get; set; }
        public Nullable<System.DateTime> o_CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Points> Points { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
