//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electric_Scooter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int a_Id { get; set; }
        public Nullable<int> a_Type { get; set; }
        public string a_UserName { get; set; }
        public string a_Password { get; set; }
        public bool a_State { get; set; }
        public Nullable<int> a_c_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
